//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.03 at 04:34:38 PM EEST 
//


package com.ayanahmedov.etl.api.dsl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BigDecimalValueFormatter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BigDecimalValueFormatter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="source-locale" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="target-locale" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BigDecimalValueFormatter", propOrder = {
    "sourceLocale",
    "targetLocale"
})
public class BigDecimalValueFormatter {

    @XmlElement(name = "source-locale", required = true)
    protected String sourceLocale;
    @XmlElement(name = "target-locale")
    protected String targetLocale;

    /**
     * Gets the value of the sourceLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceLocale() {
        return sourceLocale;
    }

    /**
     * Sets the value of the sourceLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceLocale(String value) {
        this.sourceLocale = value;
    }

    /**
     * Gets the value of the targetLocale property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetLocale() {
        return targetLocale;
    }

    /**
     * Sets the value of the targetLocale property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetLocale(String value) {
        this.targetLocale = value;
    }

    public BigDecimalValueFormatter withSourceLocale(String value) {
        setSourceLocale(value);
        return this;
    }

    public BigDecimalValueFormatter withTargetLocale(String value) {
        setTargetLocale(value);
        return this;
    }

}
