//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.31 at 01:58:25 PM CEST 
//


package com.ayanahmedov.etl.api.dsl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;


/**
 * <p>Java class for CustomConstructor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="CustomConstructor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="className" type="{http://www.ayanahmedov.com/CsvTransform}JavaClassName"/&gt;
 *         &lt;element name="parameter" type="{http://www.ayanahmedov.com/CsvTransform}ConstructorParameter" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "CustomConstructor", propOrder = {
    "className",
    "parameter"
})
public class CustomConstructor {

    @XmlElement(required = true)
    protected String className;
    protected List<ConstructorParameter> parameter;

    /**
     * Gets the value of the className property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getClassName() {
        return className;
    }

    /**
     * Sets the value of the className property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setClassName(String value) {
        this.className = value;
    }

    /**
     * Gets the value of the parameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the parameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ConstructorParameter }
     * 
     * 
     */
    public List<ConstructorParameter> getParameter() {
        if (parameter == null) {
            parameter = new ArrayList<ConstructorParameter>();
        }
        return this.parameter;
    }

    public CustomConstructor withClassName(String value) {
        setClassName(value);
        return this;
    }

    public CustomConstructor withParameter(ConstructorParameter... values) {
        if (values!= null) {
            for (ConstructorParameter value: values) {
                getParameter().add(value);
            }
        }
        return this;
    }

    public CustomConstructor withParameter(Collection<ConstructorParameter> values) {
        if (values!= null) {
            getParameter().addAll(values);
        }
        return this;
    }

}
