//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.31 at 01:58:25 PM CEST 
//


package com.ayanahmedov.etl.api.dsl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ElementConstructor complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ElementConstructor"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="sourceBindPattern" type="{http://www.ayanahmedov.com/CsvTransform}SourceBindPattern"/&gt;
 *         &lt;choice&gt;
 *           &lt;element name="constructorClass" type="{http://www.ayanahmedov.com/CsvTransform}CustomConstructor"/&gt;
 *           &lt;element name="dateValueConstructor" type="{http://www.ayanahmedov.com/CsvTransform}DateValueConstructor"/&gt;
 *           &lt;element name="stringValueConstructor" type="{http://www.ayanahmedov.com/CsvTransform}StringValueConstructor"/&gt;
 *           &lt;element name="intValueConstructor" type="{http://www.ayanahmedov.com/CsvTransform}IntValueConstructor"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ElementConstructor", propOrder = {
    "sourceBindPattern",
    "constructorClass",
    "dateValueConstructor",
    "stringValueConstructor",
    "intValueConstructor"
})
public class ElementConstructor {

    @XmlElement(required = true)
    protected String sourceBindPattern;
    protected CustomConstructor constructorClass;
    protected DateValueConstructor dateValueConstructor;
    protected StringValueConstructor stringValueConstructor;
    protected IntValueConstructor intValueConstructor;

    /**
     * Gets the value of the sourceBindPattern property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceBindPattern() {
        return sourceBindPattern;
    }

    /**
     * Sets the value of the sourceBindPattern property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceBindPattern(String value) {
        this.sourceBindPattern = value;
    }

    /**
     * Gets the value of the constructorClass property.
     * 
     * @return
     *     possible object is
     *     {@link CustomConstructor }
     *     
     */
    public CustomConstructor getConstructorClass() {
        return constructorClass;
    }

    /**
     * Sets the value of the constructorClass property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomConstructor }
     *     
     */
    public void setConstructorClass(CustomConstructor value) {
        this.constructorClass = value;
    }

    /**
     * Gets the value of the dateValueConstructor property.
     * 
     * @return
     *     possible object is
     *     {@link DateValueConstructor }
     *     
     */
    public DateValueConstructor getDateValueConstructor() {
        return dateValueConstructor;
    }

    /**
     * Sets the value of the dateValueConstructor property.
     * 
     * @param value
     *     allowed object is
     *     {@link DateValueConstructor }
     *     
     */
    public void setDateValueConstructor(DateValueConstructor value) {
        this.dateValueConstructor = value;
    }

    /**
     * Gets the value of the stringValueConstructor property.
     * 
     * @return
     *     possible object is
     *     {@link StringValueConstructor }
     *     
     */
    public StringValueConstructor getStringValueConstructor() {
        return stringValueConstructor;
    }

    /**
     * Sets the value of the stringValueConstructor property.
     * 
     * @param value
     *     allowed object is
     *     {@link StringValueConstructor }
     *     
     */
    public void setStringValueConstructor(StringValueConstructor value) {
        this.stringValueConstructor = value;
    }

    /**
     * Gets the value of the intValueConstructor property.
     * 
     * @return
     *     possible object is
     *     {@link IntValueConstructor }
     *     
     */
    public IntValueConstructor getIntValueConstructor() {
        return intValueConstructor;
    }

    /**
     * Sets the value of the intValueConstructor property.
     * 
     * @param value
     *     allowed object is
     *     {@link IntValueConstructor }
     *     
     */
    public void setIntValueConstructor(IntValueConstructor value) {
        this.intValueConstructor = value;
    }

    public ElementConstructor withSourceBindPattern(String value) {
        setSourceBindPattern(value);
        return this;
    }

    public ElementConstructor withConstructorClass(CustomConstructor value) {
        setConstructorClass(value);
        return this;
    }

    public ElementConstructor withDateValueConstructor(DateValueConstructor value) {
        setDateValueConstructor(value);
        return this;
    }

    public ElementConstructor withStringValueConstructor(StringValueConstructor value) {
        setStringValueConstructor(value);
        return this;
    }

    public ElementConstructor withIntValueConstructor(IntValueConstructor value) {
        setIntValueConstructor(value);
        return this;
    }

}
