//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.08.03 at 02:02:00 PM EEST 
//


package com.ayanahmedov.etl.api.dsl;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TargetStringFormatter complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TargetStringFormatter"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;choice&gt;
 *           &lt;element name="formatterClass" type="{http://www.ayanahmedov.com/CsvTransform}CustomFormatter"/&gt;
 *           &lt;element name="dateValueFormatter" type="{http://www.ayanahmedov.com/CsvTransform}DateValueFormatter"/&gt;
 *           &lt;element name="stringValueFormatter" type="{http://www.ayanahmedov.com/CsvTransform}StringValueFormatter"/&gt;
 *           &lt;element name="intValueFormatter" type="{http://www.ayanahmedov.com/CsvTransform}IntValueFormatter"/&gt;
 *         &lt;/choice&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TargetStringFormatter", propOrder = {
    "formatterClass",
    "dateValueFormatter",
    "stringValueFormatter",
    "intValueFormatter"
})
public class TargetStringFormatter {

  protected CustomFormatter formatterClass;
  protected DateValueFormatter dateValueFormatter;
  protected StringValueFormatter stringValueFormatter;
  protected IntValueFormatter intValueFormatter;

  /**
   * Gets the value of the formatterClass property.
   *
   * @return possible object is
   * {@link CustomFormatter }
   */
  public CustomFormatter getFormatterClass() {
    return formatterClass;
  }

  /**
   * Sets the value of the formatterClass property.
   *
   * @param value allowed object is
   *              {@link CustomFormatter }
   */
  public void setFormatterClass(CustomFormatter value) {
    this.formatterClass = value;
  }

  /**
   * Gets the value of the dateValueFormatter property.
   *
   * @return possible object is
   * {@link DateValueFormatter }
   */
  public DateValueFormatter getDateValueFormatter() {
    return dateValueFormatter;
  }

  /**
   * Sets the value of the dateValueFormatter property.
   *
   * @param value allowed object is
   *              {@link DateValueFormatter }
   */
  public void setDateValueFormatter(DateValueFormatter value) {
    this.dateValueFormatter = value;
  }

  /**
   * Gets the value of the stringValueFormatter property.
   *
   * @return possible object is
   * {@link StringValueFormatter }
   */
  public StringValueFormatter getStringValueFormatter() {
    return stringValueFormatter;
  }

  /**
   * Sets the value of the stringValueFormatter property.
   *
   * @param value allowed object is
   *              {@link StringValueFormatter }
   */
  public void setStringValueFormatter(StringValueFormatter value) {
    this.stringValueFormatter = value;
  }

  /**
   * Gets the value of the intValueFormatter property.
   *
   * @return possible object is
   * {@link IntValueFormatter }
   */
  public IntValueFormatter getIntValueFormatter() {
    return intValueFormatter;
  }

  /**
   * Sets the value of the intValueFormatter property.
   *
   * @param value allowed object is
   *              {@link IntValueFormatter }
   */
  public void setIntValueFormatter(IntValueFormatter value) {
    this.intValueFormatter = value;
  }

  public TargetStringFormatter withFormatterClass(CustomFormatter value) {
    setFormatterClass(value);
    return this;
  }

  public TargetStringFormatter withDateValueFormatter(DateValueFormatter value) {
    setDateValueFormatter(value);
    return this;
  }

  public TargetStringFormatter withStringValueFormatter(StringValueFormatter value) {
    setStringValueFormatter(value);
    return this;
  }

  public TargetStringFormatter withIntValueFormatter(IntValueFormatter value) {
    setIntValueFormatter(value);
    return this;
  }

}
